sudo: required
dist: trusty

language: node_js
node_js: 6

env:
  global:
  - secure: Lh8qR/5hTThKoslDk9G7VO7sWRVREuslEM3qVvex4lEM0Jorr0zTy5OkdL8cyiUmKxLiJkbsOIxU/nTYDVjyH0rDb1Q2bl9MsU/nPtP9FQQeNMYy5xgJFML/NfRKtKMMDV3I1b6ts512Cz9vhN4BMwkl1I0FJgZVAf5t89pS4T/kcrGzUFdvR1tWjiJNkoDll4qcmQH7Jj6+6eU6zHxyYwqrVqG1cn46YDOYn+i6zKPpJiP6GVOMWYi8BufrPMLQ47pT/eft1VZhTwjv9dFErrfAaC9GpCiQOAw5z3p6qLL16GjkOGJo+1HewrqOZ0S8OUyVSgl5pYs0c6/ddps7ywpWHRChoQRtJooh2Nqx0tZz9z+I3nUgPMc2AX8jb7bh/0jUPWTQMO7kYnlYEJskBkbh0nxmQ6+R5bFi3Hy9m1xiPz8OJEVxfXqVsE5hgdGrLMTPDSwYCjJ+xirXT8zIV3/oriuiHcuvUH3nYVH5/wnVTdiTAyr4GpIPpOb1jZBhmrJ9DgyAb4wVHY1nHtycWTppS0kh7v9uC4kqOvtVgZaEDKjyq9YaFUwDwxnIHV1iBMaqfXnW2wM9OZoqsbCkGQDwfpkAcy+i+Bx1hu2+t/KuCE0YGEjGG+OSBn3Ilp0tL5WhjbW7HjD5pmTFPQWPOnwBp+jLkKgsSkKaPjOs3PM= # DATABASE_URL
  - secure: DWsKPuKA3QvUNFRwFUjIRWTk3rOk6vgLCy9NNcRGIh74x07yv359IK/HChAnOhPESJIIi+8bG7DNCH3vlw2FaNSqvmm0KODZkZaQBV4JqbLe4CQjhmkI4mSK5tEWLJzUTTZxbpws9vUkQqvBprHwZts8pg7XAgGxKpzkss1eTzTcuhD+LVaHvKACFSWMB21G9LfuZEJY6F64L6IYl1zJUwkknBV3yn5nS/CdX+rls+dZfixLM2mzfpXq4UtaAFQqeSRrtBdRstmln+vWmRCN4SboKBH7OgeFZfKod4CTnPk8cd/RumiCPV+L5KedaoVvR1Gswywrq5wm1D5eh3fRSUQosMMUFHTEwSeAWg/vMrG4JLnGKn+vRpdtD56Gj+09OgycgcoMrhXAkBZ5mRVzQnnf7foI9UkDdDIKl4E/vT2ZCtmcBqOzgGAVYHBkegLPkSEuNqpZ/pwdykSxYPOgL2ErBB09i4dzd5jS1li4berOL8yteI9jizY26bXNlZNq8wk4B3GNRW8OFrMJAHCI6SJMqOowf7MwyCvJZzJxixMNFszS7m1wXzkd8jcLig3Cw8okJjKvvFlrA/uEJumHJ3HqeZKLDuH2+kIXhmGsEQkLh+AQUWh1hTI3/htoPt8aQwNl+a2IHf/f4StUAU3ONy8wmDGnPnV4S0nvZcSdCs4= # AWS_ACCESS_KEY_ID
  - secure: xBo1i6lFO0oEudEWMbknu76ZTkmFbT5xa4M0Da7ydU9+cd+tIC7ry49C7DD6i/pOUkKALrry/W/skb6zxUHDspVNn/5AVqmwrW0IO8o6HP8GCioWWIQSWxl6ThrwMq9TodXvzsjeBo0+TuiLqdhR+VvOBsOpdUqHXVxZhiyxEkANZ49Es2WHpapDjjX67otDztQBeUkOam7+8ZQ2wSYTd41Uf9JwlpGlCEMiKIkYiE7er6ppjGQY79sxLgSh1dh/L0Qk9A1prBOMdHGneTS2K2XkVIROyzHxBzsJZsi4ZeYMMw2DHmAKOI83I0HZI/3l3Z5+qPbx5mrxlo45VjeKoompy/JMd7VS08zNAm3REvTg6CmfDAYO7mLb4KZvzZN2vjQTA+YxaRP8H7TTkqgmkIhZcjVMnrpROk6rSZPpuJnCUdn6ZlgdOb9d31mPBdc6k0FFy1A46k81vZxMNmz4VcPrUoQ01ur+ojpJunDSItCX/jp4F7fl7GDQjPhQ9Vzyf4nEJVJOkMooPCmYSBlq9ZEk7c9mm86tv00rf/JLawWtkC1tmFK5lGPoWQi9muB1rn0I+yoklgQQTRm8W4PgjAohV9utjvaaNgap8MI5dqMm8tMv8wLKiLU0ku7l/Gs9CEUcd1bnWXN1CrYzrJbkyos1IerXjZg2/LxBiT78V2Q= # AWS_SECRET_ACCESS_KEY
  
branches:
  only:
    - master
  
before_script:
  - export PATH=$PATH:$(yarn bin)
  - lix download

script:
  - haxe tests.hxml
  - haxe build-prod.hxml
  - serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY --profile lix
  - serverless deploy --stage production
