sudo: required
dist: trusty

language: node_js
node_js: 6

env:
  - secure: "cvSQovV7FeNmGEUt8zxEsu/aaqgbQhlz4CN5yEAheSZTMGS09/iNZ3SslEglgD59rCkzbVXfxkGt+eVXDgqOi2+TfaGKauCfKXhnmvkgKnD2tVB2Y2E6JIotYy5hi3HAumcuxTAyvdembG5NHBJ9LLJUDZQ4VKV55hNJIA3OLMn+tVlz1g+HPx0NrFrGY4mrsN4lr6QfgEyWmK+JBXlhm5JFkN/KBG9doSN2H2n1opzSyH+wlboLtsZduTpukiR3JwBhqJMdypErmyKXvmC3CeXCh3hIKo2ow/qPIjxDRcu5gB2llmkabz4vDDlkpw9ofrTlc7KfsVWHIWECPL2m6RKbuJyQiormJVXsm580fOpIMe01fDkTLofvkbk7Miso9CpgVigVswGt5y9gdq+rR6x8C6aOx8nEGeS+1ZSrZQBO6DsSuMDT0RoDryr8IfGaOqdMWwd3t4/0Ge+E/mBgQyGaUji4bwF7vrKYGa6rq5Bsl0JUpmZ/JGZaue+KRIXuRbDiZMjPa6JSHn9hNSluzy/1cfZt74NB+mgGTFgQTR5/sG+o37l7dxiesdF5qVc0uGLwaaljdCLG+JET43df/sxBMh1SECegYfpn8LHlGKP/67stsMP4Uy4PqJtEVTgV/rdYdz4/VNJ33sibZ+TTksNhuIs+HDK41IOCy8ioSNM=" # DATABASE_URL
  - secure: "bmLIkj54V0pNrmqM32GctYxLRIrqyQc02ToYF1kMeK9ra6Qyrxd/DrFiccbsc225KObfPx6LWEoNeCIXT84FmpKJyfawwN6VPU9EOtIdJjQPOBUHsLmKSrTKCAsEDixFNiJXHo6FpNcoEC6Qm3t5l0A0TStcNzIt+pgBW1cn4l/ZW/6ZA+g0T3D7rVthUeJZvAts2892Mi4vZ+FMVeI6FcPvcbYcj1gmu+9nUxXLER5KDrr3mXjOgplyLXPaV5+85/CREXaMOt0UvxJbOLLaZZVorW+rGyCmMb/HaczMr0qcafrZHFmvgTii84Nw2DkdCj3kU7D3Nj3W1/Y0+VifLCsYSY4dn+5Yd5kQR+M/UEjUy/65Pv9gpFk9qh1/UfezMRlZi3CNpmuoztCxg68LS1gOjpDRAhDYj3QL6og0uK409s2PyT61pKhc57jU0js3G29DvN9Z1ponFp89ecmOMgChS2X9RZvEh+cPsq0YZx3rnJOnuEWTWPzNCirlBmLnu/hwVl0+H4+O2TjwIUxcs0MMkpsG3GENRiEERrGc9/rMSphd9A6qvqc5CCNC4KHq82cFqVj4J7Y4WseDVvwlKbGYPsohtucMIOugi7BHnqb92zE2ZhVYI0lEW0q5iptAuyBA+ufQifXpIrRokTriYmjzRBhUReuhmEsG7wL+RF4=" # AWS_ACCESS_KEY_ID
  - secure: "R0v7p/39sL8Cn2rKSHvi84staTAXNzzHvfaXKOgmq4EGIuk8w9TC4agsWpPIsGbtSz2HebfbatGjODAxrmxRPQDuDlEp/N2Bans/zxpzlTjT0DlWuL3TNOW1iJwnO7TumLBC2NR9lT5lRrhoG1BLwUT+tfgPaDlyoKRP2qykW4qb27L9p3l8SG47cPIlI+GBOEky8hUvk/XRMAIpUZk6viODN4RF+as4ggDAkBNtf7sHIhDuiZ/RknyWAX99ieNm+w1W6tvMmNN+MClvYXwDghHz9nkTDPLtm/pKzMw2Q9KR0BuMtw5mCm43vB4hPrDgfZDOiYV9p4Wda8G/GFjv/ZA+Mi8FN+JRR/sZ/sLwNDSILkKQANU9EfdYvoHPqNLqpeMRM4AjVAEOROCQCNkxRZcJYE4aQ7CLk+bS52uR67gA9sLcoejD42Hi4F/LZuXzhjU19jkYpJuUjV0grf/W7AqUbXRm1yvoyRyXkC8qGgIp+KtwfMy6mY3YOqPwmUMEQs4+j9+otiTR1Ld3FKuKwELhldDVZLCYv4KpE8EU7+DpxoHZrz4Ee88qzqWjOjI6qOUpgYNLMCkTqBVJ5RfhGxpuWGwX/Eqi5pKT04ywdh54lqT56ZvFchPQgjiXz9R8SmElTjJrh0GwovKCGRYNi08Le9n6+eGwbZ4vJ1/7e0A=" # AWS_SECRET_ACCESS_KEY

branches:
  only:
    - master

before_script:
  - yarn
  - export PATH=$PATH:$(yarn bin)
  - lix download
  
script:
  - haxe build-prod.hxml
  - serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY --profile lix
  - serverless deploy --stage production